#!/usr/bin/env php
<?php
$filename = @$argv[1];
if (!file_exists(__DIR__."/$filename.json")){
    echo "root/niwango以下に「動画番号.json」というファイル名でニワン語を含むコメントを保存し、「convert 動画番号」と実行してください\n";
    exit(1);
}
if (file_exists(__DIR__."/$filename.niwango")){
    echo "すでに同名のniwangoファイルが存在しますが、上書きしてもよろしいですか？(y/N)";
    $input = trim(fgets(STDIN));
    if(!preg_match("/y(?:es)?/i",$input)){
        exit(0);
    }
}
$json = json_decode(file_get_contents(__DIR__."/$filename.json"),true)["data"]["threads"][0]["comments"];
array_multisort(array_column($json,'vposMs'), SORT_ASC, $json);
$data = [];
foreach($json as $key => $value){
    if(strpos($value["body"],"/")===0){
        $data[]="[tm".($value["vposMs"]/1000)."]\n#".implode(" ",$value["commands"])."\n".mb_substr($value["body"],1);
    }
}
//@unlink(__DIR__."/$filename.json");
file_put_contents(__DIR__."/$filename.niwango",implode("\n",$data));